### ISSUE TITLE
SPIKE: Determine the analytics and reports to be configured for PrimoVE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1090]
Because Primo VE is used differently than discoverE, I would like to meet and discuss how we should configure analytics and reports. We will need to look at any specific analytics or reports that can be used for the Services Page View and the Articles Plus view. 

![PrimoVE ReportsandAnalytics.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/a63c09d5-793c-49e1-85a4-ac0fa460e2e8)

**Comment by lisahamlett** [comment]
Here are the files for January 2022 to date:
[https://app.zenhub.com/files/295449627/d0185be3-7b70-404d-84c2-c2fc129a9c8b/download](https://app.zenhub.com/files/295449627/d0185be3-7b70-404d-84c2-c2fc129a9c8b/download)
[https://app.zenhub.com/files/295449627/2fb7fc0a-e433-4e5e-b46e-11d0f444b4d0/download](https://app.zenhub.com/files/295449627/2fb7fc0a-e433-4e5e-b46e-11d0f444b4d0/download)
[https://app.zenhub.com/files/295449627/6218f640-f812-47df-b756-7c8fcf50b376/download](https://app.zenhub.com/files/295449627/6218f640-f812-47df-b756-7c8fcf50b376/download)
[https://app.zenhub.com/files/295449627/f7ac4e1a-77a0-4e37-b25c-32c140e5b991/download](https://app.zenhub.com/files/295449627/f7ac4e1a-77a0-4e37-b25c-32c140e5b991/download)

Note: Popular Searches and Zero-Result Searches don't populate until the end of the month, so that data isn't available yet.

**Comment by lovinscari** [comment]
Closing this ticket and will incorporate this into to overall plan for Library Search Reports.
