### ISSUE TITLE
Document process for updating newly acquired items

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1217]
- [ ] It was determined in ticket [#1118](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1116) that for now the process of updating newly acquired will be manual. 
- [ ] This information should be updated as part of the support playbooks to ensure all of Core Systems is aware of how the process runs.

**Comment by lisahamlett** [comment]
If @bwatson78 wants to talk about how we can do this in Blacklight instead, feel free to schedule a meeting.  I have some thoughts.  Or we can wait -- it's not a huge rush.  Damn thing has been broken for 3 years.  A few more weeks is not the end of the world.

**Comment by bwatson78** [comment]
@lisahamlett That change from Alma to Blacklight might get very complicated. I do suggest a meeting, and I recommend both @lovinscari and @rotated8 attend because it may involve designing a solution that doesn't work the same way as the facet does. Preview of my thoughts: If we can get the records' date acquired into a field, we can create a custom search page like ejournals that only returns those that meet a date range of acquisition. The problem doing another solution is that, if we are currently only updating records via indexing, then that means we can only process that change when the record is updated in Alma. If we shift away from that type of processing, that means we will have to learn how to manipulate Solr record values outside of indexing, which we have not done on any of our projects (to the extent of my knowledge.)

**Comment by lovinscari** [comment]
Keeping this in new issues knowing we have to look at the permanent fix for this at some point. For now, I will close this ticket since the requirements have been met but will need to find a permanent fix for this as part of Phase 2.
