### ISSUE TITLE
Solr Strategy

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#13]
SPIKE: Members of the Blacklight Discovery Layer Technology Team are asked to strategize and present to the product owner and other members of the Scrum Team a strategy for a Solr Index. Acceptance criteria for the strategy include:

- [x] Version / Type of Solr to be used
- [x] The proposed strategy for boosting items in the catalog
- [x] Scalability of the index 
- [ ] ~Sustainability of the index~
- [x] Performance of the index
- [ ] ~Future considerations including possible joining other solar indexes~

**Comment by lovinscari** [comment]
The Blacklight Wiki has been updated to include a page for technical documentation (a table of contents) and a template for a how-to-article for Solrmarc. Feel free to add or update as necessary. https://wiki.service.emory.edu/x/KR6_Cg

**Comment by rotated8** [comment]
First pass is here: https://wiki.emory.edu/display/BDL/Solr+Strategy

**Comment by mark-dce** [comment]
@tmiles2 @lovinscari I can't get to either of the two wiki links in comments above.  Can you check that I and the rest of the DCE team has access to the necessary wiki pages?

**Comment by mark-dce** [comment]
I've updated the wiki with some additional thoughts and notes.  In summary:
* We should think about "recovery from catastrophic data corruption:" rather than backup and restore - it may be faster, easier, or more consistent with regular operation to just rebuild the solr index from Alma than to have an out-of band data-imaging solution.
* Performance and scaling benchmarks should be driven by end-user facing statistics. A clear diagnosis of where the bottlenecks lay - i.e. optimizing solr will have little impact if the Rails application or Web server are the actual bottlenecks handling public user traffic.

**Sustainability** I'm not sure what we mean by "sustainability of the index" - should we break this out into a separate ticket and try to define what the measurements or evaluation criteria are for "sustainability".  Part of me wants to argue that Solr is just a cache of Alma data and that sustainability concerns and processes should be addressed at the source system in Alma.

**Future Concerns** I don't think we have enough concrete requirements at this time to do anything but guess about "Future considerations including possible joining other solar indexes".  Agile best practice is to hold off on this types of guess as long as possible, preferably until concrete requirements emerge.
