### ISSUE TITLE
Discuss and implement second pass mapping for electronic vs physical resources

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#147]
Now that we have updated the SolrMarc version and can use conditional statements, we need to map electronic resources better than last time and consider other tags, such as 006, 008, 880, leader, etc.

We will need to setup time for us to discuss this. Will try and sit down with @lisahamlett @bwatson78 @alexBLR and @AGCooper on Monday. Meeting invite has been sent to all.

**Comment by laura-ake** [comment]
@devanshu-m @lisahamlett    Note that Primo norm rules for "Top Level" facet, assigning the "Online_Resource" code, are based on a field delivery_delcategory which I haven't transcribed for you.  That field doesn't reference MARC fixed fields at all.  It gets its information from, first, special Alma-Primo publishing fields AVE and INT, which have codes translated into 3 statuses ALMA-E, ALMA-D (which we don't have), or ALMA-P .  

If those rules don't determine a status, it looks at presence of 856 4 with second indicator blank, 0 or 1.  There are some conditions that certain lowercase text strings are NOT contained in a subfield 3, y or z (example:  table of contents) because ... long story, we need another indicator for "part of resource" but it hasn't passed yet).

If you can look at documentation for those Primo publishing subfields, and figure out what equivalent data would be in your 998 (it might be, just having a 998 is condition enough, indicating there's a portfolio), you might be able to simplify.

I fear that fixed field coding may not be reliable for making this sort.  Sometimes we have attached electronic portfolios to bib records for physical items, or have added 856 URLS to them.

Let me know if you need more.  I have a doctor appt. this morning but hopefully will be ok this afternoon.

**Comment by devanshu-m** [comment]
New tickets created for second pass mapping. Closing this.
