### ISSUE TITLE
Implement api for the "get it" tab

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#160]
Dead simple implementation-
- not worrying about Emory shib auth
- avoid auth where possible
- use the alma sandbox
- no "my account" functionality

**Comment by devanshu-m** [comment]
Is this what we want?

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/b3bc4d0d-3c9d-4694-9b1f-6ef6f818606d)

**Comment by devanshu-m** [comment]
Moving this back to in sprint and waiting for research with blacklight-alma gem that Brad is doing in ticket #

**Comment by devanshu-m** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
self and alma url

https://github.com/tulibraries/tul_cob/blob/main/app/controllers/users/omniauth_callbacks_controller.rb
^ alma login session cookies

**Comment by lisahamlett** [comment]
https://developers.exlibrisgroup.com/blog/integrating-blacklight-with-alma/
"Update (February 2021)– Due to the increasingly strict security requirements of browsers, the iframe-based mashup approach is no longer recommended. This blog and demo were updated to the current best practice, which is showing availability in the discovery layer while linking out to the Alma services page for fulfillment services."

Services Page: https://na03.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView

**Comment by lisahamlett** [comment]
Sandbox
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView&rft.mms_id=990022757740302486

Production
https://na03.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView&rft.mms_id=990022757740302486

Login
bukowski1
Bukowski123

**Comment by devanshu-m** [comment]
@bwatson78 @alexBLR Whoever picks this up, please continue working in the request-options branch.
