### ISSUE TITLE
Associate Emory Shib signon with Alma 

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#162]
user signing into Emory Shib should be logged into Alma

**Comment by devanshu-m** [comment]
Update:
request-options branch is now on blackcat-arch.
Scenario:
 - When I login to blacklight on arch, I believe SSO also logs me into alma automatically. At this point, if I want to request physical copy for an item, the lightbox does not ask me to login to alma since we are already logged in. However, after a certain amount of time, when I try to retrieve physical copy for any item again, I am asked to login to alma in the lightbox, even though I am logged into the blacklight app. This, I believe is due to alma's shibboleth session timing out.

^ is this enough information to have a discussion about next steps?

**Comment by lovinscari** [comment]
@devanshu-m: I am trying to test this issue this morning but have not found an item where I can request a physical copy therefore I am not sure if I can successfully test the logout sync between the application and Alma. I'll keep looking.

**Comment by devanshu-m** [comment]
@lovinscari I apologize. I thought the branch with request options was deployed to arch, but that doesn't seem to be the case. Once the new release is deployed, I will ping again so we can test this.

**Comment by devanshu-m** [comment]
@lovinscari this should now be testable on blackcat-test
