### ISSUE TITLE
TASK: Single item reindexing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#256]
- [x] Add new rake task
- [x] Set up testing

**Comment by bwatson78** [comment]
@alexBLR I tried this command:
`RAILS_ENV=development bundle exec rails marc_index_ingest oai_single_id=9937241630902486` and it returned zero records`
and it says it processed 0 records. It seems the issue is with this line:
`record_count = document.xpath('/oai:OAI-PMH/oai:ListRecords/oai:record', { 'oai' => 'http://www.openarchives.org/OAI/2.0/' }).count - suppressed_records.count`
