### ISSUE TITLE
SPIKE: Review anomalies with Basic Search to determine work needed to improve basic search functionality

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#273]
As the product owner, I am preparing a demonstration for the SEND Stakeholder Group and would like to review the work completed with Basic Search. In preparing the demo, I had planned to show the comparison of different searches using Blacklight compared to DiscoverE and immediately discovered some anomalies with the results between the two applications when completing the same search. The outcomes of the searches are shown in the [Basic Search Test](https://docs.google.com/document/d/1uSqde5bKtVnhwYxNpm4scp77-y_-Bj14i2A06lcnRaI/edit?usp=sharing) document. In reviewing the outcomes from the initial tests in Blacklight and Discovere, Emily Porter also reviewed (and added) a column to show the outcomes when searching SOLR directly. 

I suspect this is most likely an issue with the metadata mapping detailed in the initial requirements that most likely need to be updated. As such, I would like for the software engineers along with Lisa Hamlett and Emily Porter to review the results of the tests along with the fields currently mapped for Basic Search in Blacklight to determine what changes are needed.

Details of the work involved including metadata mapping, reindexing, and software development should be provided within this ticket so that new issues can be added as refinements for future sprints. As the product owner, I will prepare the demonstration as planned and explain to the SEND team that future refinements will be forthcoming to improve the search results. 

I am unsure of the length of time needed to complete this review but suspect because of the number of people involved in the discussion and research, a minimum of an 8 is needed for this ticket.

**Comment by eporter23** [comment]
@lovinscari @mark-dce and I just met to review the basic search test document again, and we'd like to recommend a few next steps:

- Switch the Keyword search option to point to the full text of the MARC record (forthcoming ticket) so that we immediately get many more results for the searches you identified.
- Focus our efforts on identifying relevancy or search tuning needs, especially after we implement the next mapping revisions, instead of spending too much time analyzing details about Primo results vs. Blacklight results
- Run through your test searches again after we've implemented new mappings and Keyword search changes

**Comment by mark-dce** [comment]
Ditto what Emily suggests 👍
