### ISSUE TITLE
Examine and refine security headers with Alma Requesting IFrame 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#276]
As discussed during the Sprint Review/Demo on 2-24-21, the security headers with the Alma Requesting iFrame should be examined and refined to ensure necessary security measures are in place between Blacklight and Alma.

**Comment by tmiles2** [comment]
The SE team will meet before reaching out to the identity management team.

**Comment by devanshu-m** [comment]
Currently on the application side, we have security headers set for responses coming back from alma. However, after we send requests out from the iFrame, the csp header is not being set when receiving responses. This also happens when someone is trying to sign in via shibboleth. In order to see these errors go to blackcat-arch, open dev tools console, try logging in the app via shibboleth or try opening the physical copy block on one of the items.

Please note: We do not see this issue when trying to see physical copy status when logged out.

**Comment by devanshu-m** [comment]
Discussion from meeting: 
With our current approach of using iframes, we are seeing issues with security headers set for responses coming back from back. Some important points to note -
- exlibris suggests going away from iframe in their latest update. They believe iframes are not secure anymore and have asked users to go away from them.
- They have proposed a new strategy and alma resource link (discovery) that takes us to an Exlibris managed services page which is not a good option for us. Exlibris controls most of that container and we might have to do some learning even before we can change any features of that services page.
- APIs might be our best option. Depending on when we can get this work started, APIs is the best option we have. This way we can control most aspects of what goes on in Blacklight. We can use json responses coming back from Alma and style the page how we like.
