### ISSUE TITLE
TASK: Audit fields used for searches

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#278]
Since we first configured searches, our understanding of Solr fields has improved. We should
- [x] review the fields used in searches currently
- [x] change string-type fields to the equivalent text-type, if the text-type field exists
- [x] make recommendations for new text-type fields if needed.

**Comment by rotated8** [comment]
Related to #273

**Comment by devanshu-m** [comment]
Recommendations:
I think the fields below should have their equivalent text-type fields:
`title_series_ssim`, `author_display_ssim`, `author_vern_ssim`, `subject_era_ssim`, `subject_geo_ssim`

Question: Is `lc_callnum_ssm` unique to every record? If yes, we can keep this field's suffix as is, because we will want the user to search for the exact callnumber.

^ Please confirm notes above. I can create new ticket to update mappings for new text-type fields depending on responses.

@lovinscari @eporter23

**Comment by lovinscari** [comment]
@eporter23 is meeting with the Metadata Subgroup today to hopefully finalize some of the discussions around the single item display. I am asking her to hold off approving this issue until after that meeting since this work is related. Emily can provide more details during standup.

**Comment by eporter23** [comment]
@devanshu-m as Cari noted, we'll be requesting a number of mapping changes related to the View Item Detail page and that work is wrapping up this week, so it would probably be best to look at these fields in relation to pending changes. I agree with keeping lc_callnum_**ssm** as is, but since it isn't _ssim_ does that mean it isn't currently searchable?

**Comment by lovinscari** [comment]
I agree with @eporter23 and that any changes identified with this ticket will be addressed as we complete work on single item display and search results navigation pages. Thanks @devanshu-m for your work on this!
