### ISSUE TITLE
SPIKE: Determine requirements for implementing sort functions associated with future browse requirements

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#280]
As the product owner, I would like to determine the requirements for implementing the sort function by the categories below in an attempt to simplify the future work needed with browse. 

- [ ] call numbers

- [ ] Dewey call number

- [ ] SUDOC call numbers 

- [ ] NLM call numbers 

- [ ]  Library of Congress call numbers

- [ ] title

- [ ] subject

- [ ] author

The outcome of this ticket is to document the tasks with implementing the sort function with the associated categories including metadata mapping, indexing, development, and styling.

**Comment by eporter23** [comment]
Note, from Slack discussion, @lisahamlett confirmed the call numbers used in Primo's browse are coming from holding records (not bib records).

**Comment by devanshu-m** [comment]
Mapping (fields from above that require mapping and indexing):
- Dewey call number
- SUDOC call numbers
- NLM call numbers

After researching a bit I was unable to find existing blacklight catalog examples that use the `Browse Search` functionality offered by Primo. However, after reading through existing documentation on how it works in Primo, I think we could implement this in a rails-y way with blacklight using current solr search capabilities.

Idea:
- Blacklight currently has the ability to sort results alphabetically - we can select sort by here and it will sort results:

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/5e21b4e4-5797-447f-b364-be1ba109d23b)

; we could use that functionality along with group_by and a ruby count function to show the number of records a search term appears in. For example, if we are 'browse' searching by Title, and search for 'pizza', we could then group results that have 'pizza' in their title and sort it as the first entry and show number of records that the group has. This will be followed by the next alphabetical sort, for example, 'pizza base', now we can group all results that have 'pizza base' in its title and show count for that group, and so on.

As there are gaps in my knowledge of how search results are displayed and how sorting takes place in blacklight currently, the above solution may or may not be possible to implement. I can continue working in this SPIKE ticket to understand these functionalities as they are currently in Blacklight and figure out a way to group and count records; and document my findings here.

**Comment by devanshu-m** [comment]
Draft:
After discussion with Collin:
- The way to implement this would be trying to treat standard/normal search as faceted search. This will be called Browse search. For this purpose, we will need to figure out how facet search works exactly and document our implementation idea in ticket #303
- We believe that most work for this should be around display and sorting facet results.

search how facet display works and sorts facet results in bl

The following is documentation on how facet display works currently in blacklight:

**Comment by devanshu-m** [comment]
After discussion with Collin and Mark B:
**Call numbers** - We will need to index call numbers as single valued fields because it will be difficult to sort multi valued fields
**Title** - Should we create a new single valued field or use title_ssort field with ranges? For example, `title_ssort ASC` with search query including range as `* TO C` - this would mean starting from first value in the results up until the last value with B as the first character in title.
**subject** - We will need to index subject as a single valued string field
**author** - Should we create a new single valued field or use author_si field with ranges? Example would be similar to title.

Note: Existing title and author sort fields are dropping articles ('The') from their strings.

Example of sorting something by `author_si`

`http://localhost:8983/solr/blacklight-core/select?fl=author_tesim%2C%20id&q=author_si%3A%5BB%20TO%20*%5D&rows=10&sort=author_si%20ASC`

- ^ here, `fl` indicates the fields we want to display in our SOLR query result. The example above displays only `author_tesim` and `id`.
- `q` is the query term which is `author_si`
- `rows` is number of rows/results to display
- `sort` is which fields to use to sort results. Here we are using `author_si` and sorting in ascending (ASC).

A little bit about range queries in SOLR (this will be useful before sorting results coming from browse search in Blacklight - normal search in SOLR):
- When we query SOLR, we have the option of specifying ranges. An example of this is above in the title field description. Another example in my mind would be something like this:
q = `author_tesim:[ROW TO ROWLING]` this will include search results for ROW AND ROWLING
fl = `author_tesim, id`
sort = `title_ssort ASC`
Result:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fe8665f6-0f5c-4913-abb3-6baaff489bea)

There are a couple of other topics to consider:
- What happens when we have multiple titles, since title is multi-valued right now? We can use `title_main_display_tesim` which is also saved as multi-valued, but can be changed to single-valued field in SOLR.
- What about `bound-withs`?

Another example of SOLR search with range and sort: `http://localhost:8983/solr/blacklight-core/select?fl=author_tesim%2C%20id&q=author_si%3A%5BB%20TO%20*%5D&rows=10&sort=author_si%20ASC`

For implementation of browse search and more documentation in #303:
- #303 will deal with connecting solr from BL to write queries we define in this ticket.
- SearchBuilder for querying SOLR from Blacklight: https://samvera.github.io/building-searches.html
- We are still unsure about how to group and display counts in Blacklight for results returned from SOLR.

**Comment by eporter23** [comment]
@devanshu-m thanks for this write up! I'd definitely want to discuss further about any changes to `title_main_display_tesim `with the new mappings pending (I wanted to try adding the non-Roman/vernacular version of the title in that field, which would make it technically a multiple). I know we'll talk about these fields in more depth when work begins on the display field revisions.
