### ISSUE TITLE
TASK: Write proposal to implement "browse" search in blacklight

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#303]
The proposal should outline additional models, views and controllers, or changes to existing ones, and any modifications to indexing necessary to complete the work.

**Comment by devanshu-m** [comment]
Draft:
There are a few things to understand when talking about browse search as documented in #280:
- We need to pass a search term, a query field, a range for results, a grouping field, and a sorting param.
In order to implement the browse search functionality in blacklight, we can look at following options:
- We can continue working in the catalog_controller and add a new search field with group options as follows:
`config.add_search_field('by_author', label: 'By author') do |field|
      field.solr_parameters = {
        qf: 'author_tesim',
        'group.field' => 'author_tesim'
      }
    end`
- However, the challenge with this approach would be being able to display results correctly since the view right now is designed to display paginated single record items.

- Another approach is to have a separate controller which `include`s blacklight's catalog classes and controllers. Here we can still use blacklight config's search field but we will have the liberty to design our own view.

- Both approaches above will require setting group value to true as follows:
`config.index.group = true`

We might look at show results as facets are shown currently.

**Comment by lisahamlett** [comment]
FYI -- You might know this but HOL852 has indicator data which tells you which kind of call number you're looking at.

First Indicator (Shelving scheme)
# - No information provided
0 - Library of Congress classification
1 - Dewey Decimal classification
2 - National Library of Medicine classification
3 - Superintendent of Documents classification
4 - Shelving control number
5 - Title
6 - Shelved separately
7 - Source specified in subfield $2
8 - Other scheme 

Second Indicator (Shelving order)
# - No information provided
0 - Not enumeration
1 - Primary enumeration
2 - Alternative enumeration 

https://www.loc.gov/marc/holdings/hd852.html

**Comment by lovinscari** [comment]
@devanshu-m I do believe virtual shelf browsing using call numbers is a desired feature for browse but we could consider this an enhancement beyond the browse search function.
