### ISSUE TITLE
Spike: investigate Advanced Search plugin and options

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#370]
See https://catalog.libraries.psu.edu/advanced Penn State example, particularly for the "facet"-like limiters at the bottom of the form.

See also Will's notes for Lux in https://github.com/emory-libraries/dlp-lux/issues/218

**Comment by bwatson78** [comment]
@eporter23 and @rotated8 Initial findings:

- Penn State's Catalog app is largely using code from the `blacklight_advanced_search` plugin with only a few modifications (mostly very small Javascript tweaks). Comparing their setup to our current version of `blacklight`(7.4.1) and the `main` branch of `blacklight_advanced_search`, they have removed more code than they have added.
- They first implemented the exact structure of their advanced search page at a Blacklight version of 7.0.1, which should imply that we could do the same setup without complication. (Note: since then, they have allowed Blacklight to updated to any new version that accepts `blacklight-marc` and `blacklight_advanced_search` 7.0.* versions.)
- [This page](https://github.com/psu-libraries/psulib_blacklight/commits/main/app/views/advanced/_advanced_search_facets_as_select.html.erb) seems to be a good history of all the backbone changes they've had to do to maintain their advanced search page--it's not much, at all.
- Will's ticket brings up a lot of specific issues that don't seem to be directly addressed in the page linked above. That may be why Penn made some changes to the Javascript like they did, but it's not clear. Their initial implementation of the Advanced Search page only needed the addition of the `bootstrap-select` Javascript library, nothing more. 
- I don't feel it would be too complicated to use Penn State's code as a blueprint, if their page resembles the final product of what we're looking for. It is mostly "out-of-the-box".

**Comment by lovinscari** [comment]
@bwatson78 and @eporter23 - Let me look through the requirements matrix to see if there is anything needed beyond what Penn State offers. I will take a look at this after the demo tomorrow.

**Comment by eporter23** [comment]
@lovinscari I'm hoping to review with you the preferred fields and options that the metadata group put forward, too. @norm0  and I have these reflected in a wireframe.
