### ISSUE TITLE
Update a smaller OAI set for demoing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#379]
Because we are having problems completing the production OAI set reindex this week, we should create a more robust data sample for demoing. With the criteria below, this should create a pretty diverse set with about 200,000 records from across all libraries.

Proposal - create a new OAI set called _blacklightdemo_ 

- [ ] Populate this with a keyword search on "20th century"
- [ ] Also include the following records specifically, which unfortunately don't turn up in the keyword phrase:

9937245719502486
990027542670302486
990007024660302486
9936672301102486
990010861360302486
990010861430302486
990021940860302486"
9936570178002486
990021767040302486
9936834917302486
9937207914202486
9937240170802486
9936579830602486
9937247017002486
990036327060302486
990036478140302486
990036309240302486
990036473330302486
9936667981302486
990023258070302486
9937173819902486
990010861360302486
9936493491502486

**Comment by lisahamlett** [comment]
New set: BlacklightEmily
Parameters: where (Keywords contains keywords "20th century") OR (MMS ID equals "9937245719502486") OR (MMS ID equals "990027542670302486") OR (MMS ID equals "990007024660302486") OR (MMS ID equals "9936672301102486") OR (MMS ID equals "990010861360302486") OR (MMS ID equals "990010861430302486") OR (MMS ID equals "990021940860302486") OR (MMS ID equals "9936570178002486") OR (MMS ID equals "990021767040302486") OR (MMS ID equals "9936834917302486") OR (MMS ID equals "9937207914202486") OR (MMS ID equals "9937240170802486") OR (MMS ID equals "9936579830602486") OR (MMS ID equals "9937247017002486") OR (MMS ID equals "990036327060302486") OR (MMS ID equals "990036478140302486") OR (MMS ID equals "990036309240302486") OR (MMS ID equals "990036473330302486") OR (MMS ID equals "9936667981302486") OR (MMS ID equals "990023258070302486") OR (MMS ID equals "9937173819902486") OR (MMS ID equals "990010861360302486") OR (MMS ID equals "9936493491502486")
Items: 237,892 as of this morning
OAI: https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightemily&metadataPrefix=marc21

OAI is not yet published because Alma jobs are hung, but it will be ready when things start running again.

**Comment by eporter23** [comment]
Thanks @lisahamlett for piecing it together and @bwatson78 for hooking it up to arch!
