### ISSUE TITLE
Look into what content type is label as "Computer File"

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#38]
- [ ] What type of material is listed as Computer Files
- [ ] What are they mapped to in Alma?

Files reviewed
- [Physical Item](urhttps://emory.app.box.com/file/737394298272l)
- [Electronic Item](https://emory.app.box.com/file/737394293428)

**Comment by laura-ake** [comment]
Re:  what to do with computer files?  In my documenting the Primo normalization, I can tell how it's done there.
For defining the display resource type
First you use a routine that validates what the MARC format is from the leader, documented in [https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/020Working_with_Normalization_Rules/090Validate_FMT#ww1050405].  

If the format is Computer Files (CF):
use a mapping table based on the Type of Computer File (byte 26 of the 008 field):
Table Name	008_26_CF	
Enabled	Source Code	Target Code
true 	p              	archives
true 	h               	audio
true 	j                       website
true 	default    	        other
true 	d              	text_resource
true	        e              	databases (edited) 

For the Resource Type facet:  it basically is based on the display/type code.  There's a "Format_Mean" mapping table which may assign a slightly different code (pluralizing some terms).  E.g.,
display_type archives = facet_rsrctype archival_material_manuscripts
display_type audio = facet_rsrctype audios
etc.  There is no "computer files" value in this table.
We added a rule to try to add "Ebooks" to the resource type list.  Not sure that is working perfectly but it was highly requested from various parts of the library including one of our SEND team members.

For the Resource Type search index:  It just copies display/type code.  No Computer Files there.

So, other Blacklight-using libraries may map things differently, but Primo is more granular about things with "Computer Files" format and with some of the other formats like Visual Materials.  Books seems to be straightforward, but it could probably be broken down as well if the data supported it.  The 7 formats are Books, Computer files, Maps, Music, Continuing resources, Visual materials and Mixed materials

**Comment by laura-ake** [comment]
Sorry that formatted weirdly and the URL did not turn into a link.

**Comment by lisahamlett** [comment]
Looks like Laura answered this already.

**Comment by laura-ake** [comment]
Asking Lisa - link to the "Physical Items" chart doesn't link in this ticket - can you upload?  
Asking Lisa - can you explain how Alma assigns Bibliographic Material Type and Portfolio Material Type in Alma. 
Asking Lisa - please comment if there's anything about Alma indexing that you think would/should affect the discovery layer indexing.  
Do we have the ability to search for things in Alma where the portfolio (or item?) material type doesn't seem to "fit" computer files?  Seeing specific records and the effect in Primo might give a clue to what to expect in Blacklight.
Thanks.

**Comment by lisahamlett** [comment]
[Physical Item Counts.xlsx](https://github.com/emory-libraries/blacklight-catalog/files/5532564/Physical.Item.Counts.xlsx)
[Electronic Item Counts.xlsx](https://github.com/emory-libraries/blacklight-catalog/files/5532565/Electronic.Item.Counts.xlsx)

**Comment by lisahamlett** [comment]
Alma does not assign material types.  Bib material types come in from OCLC or are assigned by a cataloger.  I suggest talking to cataloging if you want to know why they catalog things.

**Comment by laura-ake** [comment]
@tmiles2 @lisahamlett @lovinscari 
Tiffany and Cari, can we check with DCE and see if the information I've provided answers their question given that:
1.  As far as I can tell, there's not a correlation between Alma material types, Physical material types, and/or Portfolio material types, and the mapping to Resource Types displayed/indexed/faceted currently in Primo, which is mainly based on MARC record fields, with some Alma-supplied fields mainly identifying whether the item is electronic access or what the locaion, collection and call number are if physical (holdings-level data). 
2.  If material is mis-coded in the Alma records or there is an error somewhere in how Alma is indexing them, a type of problem that has undoubtedly occurred among our over 4 million records and could continue to happen in future, due to human error:
  --it's possible resource type mis-coding could cause problems or puzlling inconsistencies for patrons in Primo, but we don't have any examples right now ('m not aware of it being reported very often by users; cataloging may have other channels for learning about problems, such as "report an error" form use).  If the reports from Alma haven't yet been shared with Sofia, it might be a good thing to let her know about them and get her perspective, but note the following:    
  -- Those records could cause similar puzzlement or inconsistency for Blacklight users, but unless we drastically change which Alma data the creation of resource types is based on for Blacklight, Blacklight it shouldn't surface any more problems than Primo does. 
  -- These are problems for Cataloging to resolve record-by-record.  
  --  So, although these reports indicate possible problems in Alma that could and probably should be investigated by Cataloging and cleaned up if possible, more research would be needed, and if Alma search is not set up to let us find the individual records involved, Core Systems might need to run special reports to get at which records are suspicious, and that would be a "mini-project" to be prioritized LATER.  I don't think anything requires us to do that now, and we could rely on experience once we're closer to a Blacklight beta to see if we are going to run into any problems.  

If DCE agrees, please close the ticket.

**Comment by lovinscari** [comment]
Closing this ticket and will open a new ticket if for some reason the data provided did not answer the questions by DCE.
