### ISSUE TITLE
Investigate set of records which have not reindexed since 3/31/21

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#386]
Based on this query in SOLR, `timestamp:[* TO 2021-03-31T00:00:00Z]`: **14,559** records in the production/full data set on the test environment have not reindexed since 3/31.

These records show timestamps between 2/27 and 3/28.

Examples from the beginning and end of the set:

{
        "id":"9936877826102486",
        "timestamp":"2021-02-27T11:13:57.005Z"},
      {
        "id":"9936878007802486",
        "timestamp":"2021-02-27T11:13:57.282Z"},
      {
        "id":"9936711802302486",
        "timestamp":"2021-02-27T11:13:57.897Z"},
      {
        "id":"9936877753302486",
        "timestamp":"2021-02-27T11:13:58.170Z"},
      {
        "id":"9936716422602486",
        "timestamp":"2021-02-27T19:12:10.692Z"},
      {
        "id":"9936719497502486",
        "timestamp":"2021-03-24T12:57:10.447Z"},
      {
        "id":"9936719368702486",
        "timestamp":"2021-03-24T12:57:41.437Z"},
      {
        "id":"9936716042602486",
        "timestamp":"2021-03-24T12:58:55.077Z"},
      {
        "id":"9936715886602486",
        "timestamp":"2021-03-24T12:58:56.868Z"},

{
        "id":"9937286312902486",
        "timestamp":"2021-03-28T04:40:37.486Z"},
      {
        "id":"9937286016502486",
        "timestamp":"2021-03-28T04:40:31.682Z"},
      {
        "id":"9937282915502486",
        "timestamp":"2021-03-28T04:40:02.485Z"},
      {
        "id":"9937282017902486",
        "timestamp":"2021-03-28T04:40:02.485Z"},
      {
        "id":"9937283017802486",
        "timestamp":"2021-03-28T04:40:02.485Z"},
      {
        "id":"9937281920102486",
        "timestamp":"2021-03-28T04:40:00.695Z"},
      {
        "id":"9937281919502486",
        "timestamp":"2021-03-28T04:40:00.695Z"},

**Comment by bwatson78** [comment]
@rotated8 or @lisahamlett I was contemplating taking this ticket, but realized I couldn't think of any approaches to testing why they weren't indexed. Thoughts?

The only thing I can think of is to reindex this list one by one and see if the processing throws any abnormalities. Anything further?

**Comment by lisahamlett** [comment]
@bwatson78 I will look to make sure they didn't fail in the OAI.

**Comment by lisahamlett** [comment]
The publishing job on 4/1 started at 07:00 and finished at 10:25 with no errors.  So it was already done by the time the reindex started at 16:53.

**Comment by bwatson78** [comment]
All of the IDs reindexed without error.

Observation: It takes one or two minutes after the CLI shows "Complete" before the records shows as existing in Solr. I'm guessing Solr first deletes, then replaces? The longest to load was 9937282017902486 (about 3 minutes). Its timestamp was nearest the time it appeared versus when it was processed by the Rails command.

**Comment by lisahamlett** [comment]
I plunked the 3000 IDs into Alma Analytics and went through bib fields to see if I could find any consistencies.  Dunno if any of this is relevant, but these are the things that were most obvious:
- 111 are physical records, 2895 are electronic
- All are bibliographic material type book
- All have non-numeric characters in the 264 c

**Comment by bwatson78** [comment]
@eporter23 and @lovinscari I marked this ticket a bug and removed the estimate. @lisahamlett has seen quite a bit of abnormal behavior from Alma recently, and I have come across some anomalies in the current indexing going on in Arch. 

My next step is to create another log that scrapes all of the ids we're actually receiving from the XMLs from Alma and compare that to the  un-reindexed records we find.

**Comment by rotated8** [comment]
Here's a query to get one of the items that is physical: `timestamp:[* TO 2021-03-31T00:00:00Z] && id:990016416280302486`

**Comment by bwatson78** [comment]
A PR will be made shortly, and my intention is to run this on the production set (or whichever set is active and the largest) once we reindex next.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/422

**Comment by lisahamlett** [comment]
I am in the process of taking the set of IDs Brad confirmed were received from Alma and running them back through Alma to republish and see if we get the same result.  If we get the same result, there is a data problem with the records that are not publishing.  If we do not get the same result, there's a problem with publishing somewhere between Alma and Solr.

**Comment by lisahamlett** [comment]
We have confirmed the number coming out from Alma and going to to Solr is not consistent.  I will work with Brad to see if we can some up with another test.

**Comment by bwatson78** [comment]
Working on a theory that the `until`/`before` options in the query string may have unintended effects.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/448

No screenshots necessary.

@lisahamlett Can you review that?

**Comment by lisahamlett** [comment]
Reviewed, but Collin added a comment.

**Comment by bwatson78** [comment]
@lisahamlett After screenshare, Collin's concerns have been addressed. 

New PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/451

No screenshots necessary.

**Comment by bwatson78** [comment]
@eporter23 Through our research and instituting new logs, we identified that Alma's OAI service withholds some records that technically should be a part of the XMLs we receive. The good news is that we have altered our full index query string so that the maximum amount of records come through. Before, we, at the bare minimum, placed a filter on the search asking for all records in the chosen set until the exact time we started the indexing. The new query string eliminates that filter, leaving the set wide open.

Below is the log from Friday
[https://app.zenhub.com/files/295449627/bb588504-6c7e-47d8-b357-e62ed45f40d5/download](https://app.zenhub.com/files/295449627/bb588504-6c7e-47d8-b357-e62ed45f40d5/download)

We were expecting 237,893 to come to the indexer, But Alma delivered 213,576 (-24,317).

After the changes today, we are now pulling 237,876 (-17). File below: 
[https://app.zenhub.com/files/295449627/bfbc3ca6-123f-453f-a1bd-0a873d283c24/download](https://app.zenhub.com/files/295449627/bfbc3ca6-123f-453f-a1bd-0a873d283c24/download)

I cannot account for the 17 missing--the query string has no restrictions now, and @lisahamlett has found no Alma setting hindering the delivery. I'm of the opinion that this is now an Alma/ExLibris hiccup that would need investigation from that side.

**Comment by lovinscari** [comment]
@lisahamlett and @rotated8 - I know the change in data will appear in Alma as the source of authority as in the 17 records Lisa referenced above that are no longer appearing in Alma. However, I am trying to recall if @rotated8 if you said there would also be an indicator in Solr noting a record had changed? I am okay with accepting this once @eporter23 has reviewed but I just want to make sure Solr is behaving as expected when changes are made to the index.

**Comment by rotated8** [comment]
@lovinscari Solr keeps a timestamp of when the record was updated, so you can ask for all the records that have been updated since a given time, but there is not an explicit "this is different" flag, or a list of what has changed. If something is removed, you would have to know what its ID was, and infer from not finding a record with that ID that it had been deleted.

All of which is to say, this appears to be working as intended.
