### ISSUE TITLE
AWS Cost Management: Identify Other Costs In AWS Reports

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#541]
Per ticket #516 there is a "long-tail" of other AWS costs that appear to be running around $700 per month. This ticket is to further explore what those costs are and if they are actually needed or if they can be decommissioned.

**Comment by libdgg** [comment]
Doing review of recent numbers to focus on the areas that increased over the past couple of months in the "other" category.

@rotated8 @eporter23 @mark-dce @mlooney @oraposa @libah @AGCooper 
Hi all, I need to confirm if the following increases are expected and if anyone knows why.

BoxUsage:t3.large($) - very large increase from 0 to 40 last month and to 270 this month

EBS:VolumeUsage.gp2($) - increased

BoxUsage:t3.medium($) - dropped to zero after hovering around 150-170

LoadBalancerUsage($) - slight increase

**Comment by libah** [comment]
T3 Medium was replaced by T3 Large, so we would expect it to be zero now and for the charges to increase for the full month of May for T3 Large.




From: Doug Goans ***@***.***>
Reply-To: emory-libraries/blacklight-catalog ***@***.***>
Date: Tuesday, June 1, 2021 at 10:27 AM
To: emory-libraries/blacklight-catalog ***@***.***>
Cc: "Hulton, Ann Gilmore" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [emory-libraries/blacklight-catalog] AWS Cost Management: Identify Other Costs In AWS Reports (#541)


Doing review of recent numbers to focus on the areas that increased over the past couple of months in the "other" category.

@rotated8<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frotated8&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783548762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sYi5XUdXb12vTGuX3RoQcK6s4JbeE7BxkjoHc%2BQKQQQ%3D&reserved=0> @eporter23<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feporter23&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783548762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xpra1KyDRdR1VvtxbORvQAAbKpB8NPrCgxw9q5yXhiQ%3D&reserved=0> @mark-dce<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmark-dce&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783558759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1U3VbZDAUK86WYIJKMrXkGT8fh1oBAnV%2B0Wp4CNF53o%3D&reserved=0> @mlooney<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmlooney&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783558759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p6Jj59FTQ6t1PLUtehlp6KK7WJEOCSA82kB0t%2FC%2FRNI%3D&reserved=0> @oraposa<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foraposa&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783568753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rB8m28UlWE4%2FISeK1n%2FQRgg3CDCqtum8OhwNWy%2BtIqo%3D&reserved=0> @libah<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flibah&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783568753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wzIb%2B%2FD%2BibW7NJX507DfwU%2Bansjg3MzKImSaTUP%2Ffqo%3D&reserved=0> @AGCooper<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAGCooper&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783578743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dxCoXMq20%2BSHbV8iAPbiYvg1Y2PikObsB8lU9WNYG8A%3D&reserved=0>
Hi all, I need to confirm if the following increases are expected and if anyone knows why.

BoxUsage:t3.large($) - very large increase from 0 to 40 last month and to 270 this month

EBS:VolumeUsage.gp2($) - increased

BoxUsage:t3.medium($) - dropped to zero after hovering around 150-170

LoadBalancerUsage($) - slight increase

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femory-libraries%2Fblacklight-catalog%2Fissues%2F541%23issuecomment-852171145&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783578743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ekQvRWoYp6R8C5bY7pbWVyWKR5I8OrTIL8eOWaugkeg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABWLKIILFO44U2FJTXB6CTTQTU6ZANCNFSM45FJ47BQ&data=04%7C01%7Clibah%40emory.edu%7C806eb58d866f42465e8a08d925097357%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637581544783588740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k4HUqvzFYQy2z9DIJIIIlyfenwEJS%2BzZSNnvUYAo69c%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by libdgg** [comment]
Thank you @libah 

Since we have awareness of the t3 changes (which was the most dramatic change in costs over the past few months) and other changes appear to be expected and trending toward stable I will close this ticket.

I will create a new ticket for a deeper dive into Cloudwatch costs as that is one of the largest continuing costs. Those costs appear more consistent for over a year but the cost is large, it includes both DLP and Blacklight and it would be good to confirm it is setup as expected.
