### ISSUE TITLE
Marc Field to Solr Field Mapping

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#57]
As a product owner, I would like a human-readable report that provides a mapping of MARC Fields that correlate to Solr Fields in order to produce a metadata model that will be used for basic search, faceted search, advanced search, search results sorting, and relevancy search.

User Acceptance Criteria:

- [x] From the previous OAI-PMH Alma Publishing Profile, the application should include a page that translates the mapping with the following information (Marc Field > Description > Solr Marc Field) into a human-readable page

**Comment by devanshu-m** [comment]
Questions for @lovinscari :

1) Do we need the full set of data right now to be able to address this ticket better? We have three alma setups we can work from - production, sandbox, and sample set (blacklighttest).
URLs provided by Lisa:
Production OAI (All Items): https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklight&metadataPrefix=marc21

Production OAI (4556 Item Samplet Set): https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklighttest&metadataPrefix=marc21

Sandbox: https://emory-psb.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklight&metadataPrefix=marc21

2) Is there a rush to get these reports in #56 and #57 or can this wait a while? I ask because the rake task right now is only setup for the blacklighttest sample set and will require some work to expand it so that it can become dynamic and be used for any set. The work done in this will also contribute to the work to be done in #74.


Answers to these questions should help implement #56 and #57.

**Comment by tmiles2** [comment]
@lovinscari I made a judgment call here so the work could progress. We will use the sample set of data to produce the initial mappings. To ensure we have the full mapping we will need the full set of data, which will require some additional work that Devanshu mention above, and may become more complex depending on the amount of production data.

**Comment by devanshu-m** [comment]
After discussions with Collin, Zo, and Brad, and looking at the urgency of this issue, we have decided to first go ahead with a simple readme file and document all the fields we are harvesting from the alma sample set. This is because we have little to no experience with marc fields and don't have a clear understanding of the mappings ourselves. This will get clearer after meeting with catalogers that Lisa setup and another one on Monday with Emily and Alex. 

I have a solution in mind to make this approach dynamic and into a page within the application, but will work on it after we have more knowledge about marc fields.

**Comment by devanshu-m** [comment]
First pass at how I understand the mappings (this is not accurate, but should be treated as only a starting point). I have documented descriptions of how I understand the fields along with their tags and codes in the description column:

https://github.com/emory-libraries/blacklight-catalog/tree/report-map/lib/tasks/solrmarc

**Comment by lovinscari** [comment]
@devanshu-m - I get a page not found when trying to access the ReadMe File on GitHub.

**Comment by devanshu-m** [comment]
Link to readme: https://github.com/emory-libraries/blacklight-catalog/blob/main/lib/tasks/solrmarc/README.md
