### ISSUE TITLE
Spike: Determine best option for clearing bookmarks cached

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#592]
Determine best method for clearing bookmarks for non-logged in users including the possibility of running a periodic kron job to clear the cache. There was thought something similar was implemented for DLP but I am not finding any tickets associated with this work. The goal is to clear the cache periodically for bookmarks that have been stored for non-logged in users. A reference point could be any bookmarks older than 30 days for non-logged in users should be cleared. Time box maximum of 8 points.

Acceptance Criteria:

- [x] Determine best method for implementing this requirement.

- [x] Document findings within this ticket.

- [x] If work needed is less than 8 points then the assignee should create a new ticket to implement the work needed after reviewing with @AGCooper and @rotated8 

- [x] If work needed is greater than 8 points then work required should be reviewed with product owner to determine timing.

**Comment by devanshu-m** [comment]
Bookmarks as they work right now:

- Guest users can add bookmarks without being logged in. When they do this, first a user object is created with the next numerically sequential id number and the uid is a string `guest_*`.
- Once the guest user object is created, a subsequent bookmark object is also created using the user's id number, document id, and document type (for our case SolrDocument)
- Now, lets say this guest user wants to sign in (in the same browser instance), once they sign in, the bookmarks that they added as a guest in that browser, will get updated with their actual user id number. Therefore, now those bookmarks will belong to a registered user rather than a guest user.

In my opinion, we should implement following strategy to clear bookmarks from guests:
- We can add a cron job that kicks off a background job weekly to clear guest user bookmarks.
- We will first find all bookmarks that were created in the last seven days.
- After that, we will run a join query that will get us all the user IDs that have the guest flag as 1 (or true). Once we have all these user IDs, we can delete bookmarks that are owned by these user IDs.
One way to this in sql is as follows:
`
delete from bookmarks where user_id IN (select * from(select users.id from users join bookmarks on users.id = bookmarks.user_id where guest=1)bookmarks);
`
- We can implement the above ^ in a rails-y way.
- This will make sure all `guest` bookmarks from last seven days are deleted.
- We can schedule the cron job to run every seven days (once a week).

**Comment by bwatson78** [comment]
@devanshu-m In your research, did you happen upon a similar link to a Guest User's search history? If so, we can notate and move that ticket to the same stage.

**Comment by devanshu-m** [comment]
MarkB suggested instead of asking cron to look for bookmarks created in the last seven days, it might be better to delete all for all guest users saved until one day before cron was run.
