### ISSUE TITLE
Spike: Determine best method for clearing search history cache

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#593]
Determine best method for clearing history for non-logged in users including the possibility of running a periodic kron job to clear the cache. There was thought something similar was implemented for DLP but I am not finding any tickets associated with this work. The goal is to clear the cache periodically for search history that have been stored for non-logged in users. A reference point could be any bookmarks older than 30 days for non-logged in users should be cleared. Time box maximum of 8 points.

Acceptance Criteria:

- [x] Determine best method for implementing this requirement.

- [x] Document findings within this ticket.

- [x] If work needed is less than 8 points then the assignee should create a new ticket to implement the work needed after reviewing with @AGCooper and @rotated8 

- [x] If work needed is greater than 8 points then work required should be reviewed with product owner to determine timing.

**Comment by bwatson78** [comment]
Initial findings:
- There is a built-in `Search` model method that deletes all unassigned searches (no `user_id` passed to it) older than X days (a number of days you pass as an argument to the method). This can easily be called from the rake task created to clear Bookmarks of Guests, as well.
```
 # delete old, unsaved searches
  def self.delete_old_searches(days_old)
    raise ArgumentError, 'days_old is expected to be a number' unless days_old.is_a?(Numeric)
    raise ArgumentError, 'days_old is expected to be greater than 0' if days_old <= 0

    where(['created_at < ? AND user_id IS NULL', Time.zone.today - days_old]).delete_all
  end
```
From my rails console I confirmed that all of the existing Searches were Guest searches, which makes sense, since I do not use a local database login for anything. 
- I wanted to see what searches looked like when a user was logged in. I created a database login and ensured that I was current_user, then performed a couple of queries that registered to the session (and therefore to the the Search History page.) This is where I learned that none of my queries performed while logged in showed in the console as retaining my user id, which means, without diagnosing this possible bug in the future, that no searches will be associated to the user. I'm now going to research the same on Lux.

**Comment by bwatson78** [comment]
@eporter23 I have confirmed that both Lux and Blacklight have the same bug: Searches are not associated to the user, just the session. If this is the desired behavior, disregard. Otherwise, I will look into the cause/resolution.

**Comment by bwatson78** [comment]
Wrapping up this ticket: performing `Search.delete_old_searches(days_old)` would wipe out all searches older than X days. I've sifted through the methods called to create searches and have seen no explicit passing of the current_user's id to the Search object creation. This may be correctable by a certain CatalogController configuration, but I've yet to find it.

**Comment by bwatson78** [comment]
@AGCooper and @rotated8 Ready for your review.

**Comment by eporter23** [comment]
@bwatson78 thanks for this information. For Lux at least, we have verbiage warning users that their search history is session based, so I am not as concerned about it. I'll make a note to discuss with @lovinscari what she'd like the behavior to be, because longer-term saved searches for catalog users may be much more significant.

![Screen Shot 2021-06-15 at 9.12.35 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/4b22118a-aaa0-439e-969f-02385ff19388)
