### ISSUE TITLE
Conduct a security scan post beta

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#616]
Per our process for the Avalon (AV Reserves) product launch, here are the steps to run the scan. NOTE: It could cause potential performance issues and/or insert garbage data into the backend. 

Step 1: Email Elliot Kendall ( elliot.kendall@emory.edu ) to run a security scan on our test environment. Include the domains for the scan: https://blackcat-test.libraries.emory.edu

Step 2: report result in this ticket for any next steps with the team and determine if any other scans are needed in our environments.

**Comment by libdgg** [comment]
@lovinscari @tmiles2 checking to see if you would like me to pursue this at this time or hold?

**Comment by rotated8** [comment]
Per Standup 11/09- we will try to scan test rather than production.

**Comment by tmiles2** [comment]
Blocked by user testing and pending dns fix

**Comment by libdgg** [comment]
I emailed Elliot to request the scan of https://blackcat-test.library.emory.edu/ today 2021-11-12

**Comment by libdgg** [comment]
@AGCooper @jcrompton42 @libah @rotated8 
Here is the response from Elliot. Please let me know what you think about his recommendations so far and his final question. Thx
.....................
I've started out by checking TLS settings and HTTP headers, and I have a couple of suggestions:
Your TLS ciphers include some that may be weak. I'd suggest using the
settings from here: 
https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Femory.service-now.com%2Fkb_view.do%3Fsysparm_article%3DKB04501&amp;data=04%7C01%7Cdgoans%40emory.edu%7C1554f650b8524379ee1608d9a61a2afa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723453582835868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=dK2hPOSwzojFCecc0hDNq2wllMLyl55AgKuUhFSvGn8%3D&amp;reserved=0

That's assuming you're terminating TLS at Apache. If it's at an AWS load balancer, you'd need to change the config there instead.

I'd suggest hiding both the exact version of Apache and Phusion_Passenger/6.0.7 from your server banner.

As far as a full scan goes, that would potentially impact performance and/or put garbage data into the backend database. Is that okay? Would it be helpful to do the scan authenticated, or is most of the application exposed for an unauthenticated user?

**Comment by jcrompton42** [comment]
I can restrict the cipher suites used and the server banner should be just a setting in apache I can change.

I think as long as the full scan is against test, it should be fine.
________________________________
From: Doug Goans ***@***.***>
Sent: Friday, November 12, 2021 4:56 PM
To: emory-libraries/blacklight-catalog ***@***.***>
Cc: Crompton, Beth ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/blacklight-catalog] Conduct a security scan post beta (#616)


@AGCooper<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAGCooper&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180561717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VTojDtPSLlOQeKzIR3nE7n3ZqZgFQfZH%2FurARprR0E4%3D&reserved=0> @jcrompton42<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcrompton42&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180571667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xQjb3YBXLZZE93VQ4Ad0T2DxU%2F57oaUpFy2VQ3TypIo%3D&reserved=0> @libah<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flibah&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180571667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P6su%2F2owvBkYMAKZfTcY2Omtftw%2BKxmk9iS5yTSGa%2BI%3D&reserved=0> @rotated8<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frotated8&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180581625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BmX5IwypEiMCgdZnAgai9C5Wob3%2FP2DslRvhRPZMi5c%3D&reserved=0>
Here is the response from Elliot. Please let me know what you think about his recommendations so far and his final question. Thx
.....................
I've started out by checking TLS settings and HTTP headers, and I have a couple of suggestions:
Your TLS ciphers include some that may be weak. I'd suggest using the
settings from here:
https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Femory.service-now.com%2Fkb_view.do%3Fsysparm_article%3DKB04501&amp;data=04%7C01%7Cdgoans%40emory.edu%7C1554f650b8524379ee1608d9a61a2afa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723453582835868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=dK2hPOSwzojFCecc0hDNq2wllMLyl55AgKuUhFSvGn8%3D&amp;reserved=0<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Femory.service-now.com%2Fkb_view.do%3Fsysparm_article%3DKB04501&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180591576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zkeO21bOpkjCplAw470F7mMO8zdQFe1bBdlf%2B%2FLPJmA%3D&reserved=0>

That's assuming you're terminating TLS at Apache. If it's at an AWS load balancer, you'd need to change the config there instead.

I'd suggest hiding both the exact version of Apache and Phusion_Passenger/6.0.7 from your server banner.

As far as a full scan goes, that would potentially impact performance and/or put garbage data into the backend database. Is that okay? Would it be helpful to do the scan authenticated, or is most of the application exposed for an unauthenticated user?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femory-libraries%2Fblacklight-catalog%2Fissues%2F616%23issuecomment-967639436&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180591576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R6HZZ8HceVQPMtMivuOdA%2BiVb0ktyeD3FxylEP6o7IU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVE63MGWIDCMLZU3DA5RJDLULWESLANCNFSM46DETN3A&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180601541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fzdg87OS4k7sDDjZenoWu%2F3hayJd%2Bm%2BafFbTaECy68g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180611492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iiYV0n4cx%2BwMHiSGVi7%2FU84FHvBflPhYNbDGhlH2KZQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbeth.crompton%40emory.edu%7Cc751422fce584b4d387408d9a62756ec%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637723510180611492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rzxoK9UuXve%2BXLPAnUed2oDt6L8IkEeNV6PELkTJOvM%3D&reserved=0>.

**Comment by libdgg** [comment]
I emailed Elliot to loop Beth into that thread and to answer Elliot's questions. I also asked Elliot to let us know when he would be doing the scan.

**Comment by jcrompton42** [comment]
the exact version of Apache and Phusion_Passenger/6.0.7 have been removed from the server headers.

**Comment by libdgg** [comment]
@tmiles2 @lovinscari @AGCooper @rotated8 @jcrompton42 Per the slack thread, I have emailed Elliot to see if he can start the scan a 5pm this Friday.

**Comment by libdgg** [comment]
@tmiles2 @lovinscari @AGCooper @rotated8 @jcrompton42 Elliot will do the scan starting Friday 11/19 at 5pm. It may not be complete by 9am Monday. I'll update this and slack when the scan is complete.

**Comment by jcrompton42** [comment]
Cipher strength has been increased, results from testssl blackcat-test.library.emory.edu are:
 Protocol Support (weighted)  100 (30)
 Key Exchange     (weighted)  90 (27)
 Cipher Strength  (weighted)  100 (40)
 Final Score                  97
 Overall Grade                A+

**Comment by libdgg** [comment]
@jcrompton42 @AGCooper @rotated8 update from Elliot about the scan are below. What do you all think?

Well, the scan only ran for about two hours before aborting with the following message. Would you like me to try again?

Scan aborted after too many timeouts

DESCRIPTION
The scanner aborted the scan due to the number of consecutive timeouts received from the web application, to prevent this latter to be completely unresponsive and unable to process normal requests.

SOLUTION
Edit scan policy and update performance settings to decrease the number of HTTP connections in parallel and the number of HTTP requests to be sent per second in order to help your web application cope with the traffic generated by the scan. At the same time, verify that your firewall has not blocked the scan and that the server hosting the web application is properly sized to deal with the traffic induced by the scan. If the issue persists after decreasing performance, verify with the developer of the application that there is no congestion or rules preventing scan to proceed normally and how to bes

**Comment by jcrompton42** [comment]
I think we should have him edit the scan policy and try again starting on Wednesday

**Comment by libdgg** [comment]
Scan completed. Here is the response from Elliot:

Good news: the scan completed successfully this time. I'm attaching the
results.

The first two items (Blind SQL Injection, Java Object Deserialization)
would be major issues if they are in fact true positives. Based on
what's in the report, though, I have my doubts. Can you check the
backend and try to determine if there's actually any SQL injection or
Java object deserialization possible on the URLs in question?

The third item (Host Header Injection) is pretty straightforward and
not a particularlly big deal. Basically, whatever value the client puts
in the X-Forwarded-Host header gets used to build URLs in the
application HTML. There's some potential for abuse, so it's safer to
use a known-good value.

The items marked Low are indeed that. They're more good security
hygiene than anything. They'd be nice to fix but shouldn't be a
priority.

Please let me know if you have any questions. Thanks.

**Comment by rotated8** [comment]
Security's SQL injection attack injects SQL into... Solr. So that one is safe. The other two high severity issues they found were vulnerabilities is Spring, the Java framework, so are also false positives in a Ruby application.
