### ISSUE TITLE
Add capitalization styles to titles in MLA and APA citations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#642]
This continues work identified in #500. Note: it may be nearly impossible to output the capitalization styles as these standards require, but we should investigate what we can achieve for each.

The MLA and APA citation formats require specific and distinct capitalization rules. The capitalization of words in titles in the catalog may vary, but don't typically match either pattern.

MLA References:
https://www.scribbr.com/mla/titles/
https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_page_basic_format.html?nt=1

> Capitalize each word in the titles of articles, books, etc, but do not capitalize articles (the, an), prepositions, or conjunctions unless one is the first word of the title or subtitle: _Gone with the Wind,_ _The Art of War, There Is Nothing Left to Lose._

APA References:

> capitalize only the first letter of the first word of the title and subtitle, the first word after a colon or a dash in the title, and proper nouns.

Example - 990027503070302486

**Current output - MLA**

Yeats, W. B. _The autobiography of William Butler Yeats: consisting of Reveries over childhood and youth, The trembling of the veil, and Dramatis personae_. The Macmillan Company, 1938.

**Desired output - MLA**

Yeats, W. B. _The Autobiography of William Butler Yeats: Consisting of Reveries over Childhood and Youth, the Trembling of the Veil, and Dramatis Personae._ The Macmillan Company, 1938.

![Screen Shot 2021-06-10 at 10.59.21 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ef484a66-f7a4-4a6e-b2f9-1513b39a297b)

**Current output - APA**

Yeats, W. B. _The autobiography of William Butler Yeats: consisting of Reveries over childhood and youth, The trembling of the veil, and Dramatis personae_. The Macmillan Company, 1938.

**Desired output - APA**

Yeats, W. (1938). The autobiography of William Butler Yeats : Consisting of reveries over childhood and youth, the trembling of the veil, and dramatis personae. New York: The Macmillan Company.

![Screen Shot 2021-06-10 at 11.31.22 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/94853265-8c56-4518-8aac-7af1ee76ac2b)

**Comment by alexBLR** [comment]
![Screen Shot 2021-06-15 at 10.42.04 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/a6f1967d-d701-4cf4-8392-47cd0eeff278)


![Screen Shot 2021-06-15 at 9.44.44 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/a6518dcc-bdab-4699-996d-4b6fbf46e80e)

**Comment by eporter23** [comment]
@alexBLR do any of the changes require reindexing in order to test them?

**Comment by eporter23** [comment]
@alexBLR here are some examples from testing - some records look very good (including most MLA), but others don't seem to show the correct capitalization.

Good examples for both styles
https://blackcat-test.library.emory.edu/catalog/990028709320302486
https://blackcat-test.library.emory.edu/catalog/9937201108402486
https://blackcat-test.library.emory.edu/catalog/9937310197902486
https://blackcat-test.library.emory.edu/catalog/9937310011902486
https://blackcat-test.library.emory.edu/catalog/9936565156402486

APA issues
https://blackcat-test.library.emory.edu/catalog/990027503070302486
https://blackcat-test.library.emory.edu/catalog/9937297878102486
https://blackcat-test.library.emory.edu/catalog/9937297772202486

**Comment by alexBLR** [comment]
Hey Emily. I think we should close the APA/MLA ticket. When we generate a citation title, we grab a naturally occurring title from MARC. Some titles are naturally capitalized and some are not, that is why we get a discrepancy sometimes. The APA title capitalization requirements would be almost impossible to achieve. The reason behind this is that due to APA rules we still need leave capitalization on proper nouns. Without using very complicated algorithms, and spending weeks developing it, it would be impossible to “find” proper nouns in the sentence and just capitalize that.

Here are some options that can be achieved:

1. Lower case the whole title and capitalize the first letter and the first letter after dash or colon. The downside is that all proper nouns will downcased in this case

2. Apply title case capitalization similar to what we in MLA: https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case

3. Leave the naturally occurring capitalization that MARC provides which will be the most inconsistent option out of 3.

**Comment by eporter23** [comment]
@alexBLR Considering the options above, I think what was most recently deployed seems to be working well for MLA and we can just leave the APA as it is, because none of the options will quite achieve it. Is that your thought as well (I guess that is number 3 above)? Thanks for the analysis!
