### ISSUE TITLE
TASK: Document Standard Sync Process for Solr and Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#74]
As the product owner, I would like to document the routine schedule for the sync between the Solr Index and Alma that updates Blacklight with new or deleted items from the catalog throughout the day, and does not degrade the production environments in Alma, Blacklight, or Primo. 

Acceptance Criteria:

- [ ] Based on performance tests presented ticket #14, once an Alma synchronization schedule is confirmed that does not cause any performance issues this task is for members of Core Systems, Infrastructure team, product owner and director of technology operations to include information in OLA for the Blacklight Product as a standard operating procedure.

**Comment by tmiles2** [comment]
Epic- Availability/Uptime

**Comment by lisahamlett** [comment]
Now that we've fixed the publishing issue between Alma and Solr, everything is working on the Alma side.

**Comment by lisahamlett** [comment]
Alma Documentation:

On the Alma side, the application has a built in OAI integration that is used for ALL OAIs published from Alma, regardless of purpose.  The link follows this format:
https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=[SET NAME]&metadataPrefix=marc21

To build an OAI, one must create a set of items one wishes to publish.  This can be all items or any group of items based on search parameters or specific titles IDs.  The main set for Blacklight is named "Blacklight" and contains all records.

Once you have a set, you create a publishing profile and add any normalization or data enrichments to it.  The Blacklight set does not normalize anything currently because it would dramatically slow down the publishing process, but it does have these enrightments:
- Linked Data Enrichment
- Bibliographic (Title Level) Enrichment as a 999 field with these subfields
    - a: suppression information
    - b: record format
    - c: brief level
    - c: creation date (pulls creation date if record imported from another system)
    - d: update date
- Physical Holdings Enrichment as HOL852 pulls any information from the Holding 852 field.
- Physical Items Enrichment as 997 field with these subfields
    - a: barcode
    - b: material type
- Electronic Inventory Enrichment as 998 with these subfields
    - a: portfolio ID
    - b: electronic material type
    - c: activation status
- Digital Inventory Enrichment as AVD, though we're not currently using this.

The publishing profile for Blacklight is currently scheduled for "Every 6 hours, starting at 04:00."
Nothing here should need to be updated unless a change to one of the enrichment fields is needed and the publishing status and history can be monitored in the Alma Jobs.

Let me know if you need anything else regarding how this is done in Alma.

**Comment by lisahamlett** [comment]
Here's Collin's documentation from the Wiki as well: https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index

**Comment by bwatson78** [comment]
Blacklight Application Procedure: 

We have a rake task in place that runs the incremental index processing four times per day (reference: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/207). The start time (the exact time the last incremental or full index started) dictates what records are pulled for the incremental processing. Any record that has been changed or added since the start time of the last full/incremental index will be passed by the OAI delivery service to the Blacklight processing and indexed, overwriting existing records and initializing recently added items. As noted in the ticket referenced above, the amount of time needed to do this will most often be less than five minutes.

For exact rake task processing times, I will request @oraposa to add them here, since I am unaware of the Ansible scripts' location on the server.

**Comment by rotated8** [comment]
I changed the page title for the wiki link, since we aren't using SolrMarc anymore. new link is https://wiki.emory.edu/display/BDL/Harvesting+data+from+Alma+into+Solr
