### ISSUE TITLE
BUG: Inconsistent information showing with Real Time Availability

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#748]
During acceptance testing, I found record 9937294718502486 is showing as a book that is available. ![RTABug.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/8fe845a5-5e1a-4fab-9e4e-870cc28036b5)

However, when selecting the request button I was not given the options of hold or doc delivery and the Services Page showed no options available. I am not sure if this is a bug with real time availability or perhaps Alma User Group Rules are preventing this item from being checked out. 

- If the issue is with real time availability it is requested this bug be resolved so that the item is not showing as available if indeed it is not available. 
- If the issue is with a suppressed record showing that should not be then it is requested the issue with suppressed records showing that should not be resolved
- If the issue is with Alma User Group rules that prevent a user from requesting the item then the developers and product owner should confer on the best solution to resolve this such as providing a message to the user suggesting the end user contact a library representative for additional assistance.

**Comment by bwatson78** [comment]
@lovinscari Can you verify your Net ID with me?

**Comment by bwatson78** [comment]
First Observations:
Alma is saying, from the availability API response, that this record does have availability, but that it contains no physical item objects. My next step is to pull the XML to see if there is anything further I can determine from it.

**Comment by tmiles2** [comment]
Something to be aware of: When trying test requesting a record, availability info (3 copies, 2 available, 1 request) is based on production Alma and hold requests results are sent to the sandbox environment - so you won’t see the request count (from production) go up when you make a hold request (to sandbox)

**Comment by bwatson78** [comment]
This is an issue with the Alma User Group rules. There are two separate API calls involved in this process:

1. Availability: this does provide us (obviously) whether the records are available and in what location and how many, but unaware of the user's capability to request those items.
2. Holdings: this query accepts the user's net_id and the record's mms_id to determine which holdings the user should see on that show page.

So, we are not seeing any hold or document/article request options because, based on the Holdings API response, we're not authorized for any of those holdings.

This does raise an issue, though. Do the rules for requesting a physical item hold and an article or document overlap? If they do, then the logic in place works as intended. If they don't, then we would have to make an extra API call to Holdings, pulling the unencumbered (by the user's restrictions) holdings, and then pass them through our current filters for Document/Articles. Alternatively, to avoid making a redundant API call to the same endpoint, we could remove the user's net_id from the call and rely on our own application's logic to filter out who can and cannot do a physical hold on the items in question.

For the rest of the time that this issue's in progress, I'll see if the rules for physical hold and document article perfectly overlap. If they don't, I'll put this into `To Accept` immediately and ask Cari/Emily their preferred approach.

**Comment by bwatson78** [comment]
@lovinscari We should breakout new tickets based upon our meeting at 07/13/2021 2p EDT.
