### ISSUE TITLE
SPIKE: Make recommendations for system monitoring and alerts

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#75]
As the product owner, I would like middleware team, technical lead, and operations team (Core Systems)  to work together to define monitoring requirements / metrics for the AWS environments of Arch, Test and Prod; Solr Index; and Blacklight application that can be reviewed against existing system monitoring tools and associated alerts to ensure environments and application is available 24x7 unless downtime has been previously scheduled and stakeholders notified. At a high level, it is assumed items to be monitored include 

- [ ] CPU Utilization
- [ ] Network Utilization
- [ ] Disk Performance
- [ ] Disk Reads/Writes
- [ ] Memory Utilization
- [ ] Any other items that could negatively impact the environments, index or application causing them to be unavailable. 

The resources identified should be continuously monitored alerts should be configured based on the severity. For example, information only alerts could be captured in a log whereas breach of metric causing unscheduled downtime of a production system should be considered a high priority alarm requiring immediate intervention. Because this is a 24/7 environment, automated recovery should be included in the recommendation for the system monitoring and alerts. 

References:
https://wiki.emory.edu/display/DLPP/CloudWatch+Alarms
https://wiki.emory.edu/display/DLPP/DLP+CloudWatch+Logging

**Comment by libdgg** [comment]
Meeting scheduled for Monday 2/22 at 3:30pm

**Comment by libdgg** [comment]
The team met to review this ticket and develop an approach for monitoring alerts. We will be leveraging two services to complete the work and address the requirements in the ticket as follows:

1. CloudWatch dashboard setup to monitor AWS components related to the ticket requirements when available (i.e. CPU, Disk, Memory, etc). While the team feels that most of the requirements will be met with CloudWatch, any requirement that is not met with will result in team exploration of alternate solutions for those partcular metric(s).
2. CloudWatch alarms configured with initial metrics to evaluate for adjusting thresholds that trigger alarms. The team will review AWS, or other industry documentation for best practices for thresholds. The team will plan a review of the alarm thresholds to test their behavior. The thresholds are configurable so we can throttle them once they are in place to mitigate false alarms or otherwise change their behavior.
3. Setup Thousandeyes to monitor blacklight which will enable us to be aware of degradation of user access to the product.
3. Setup of slack and paging will enable us to use send alerts from Cloudwatch and Thousandeyes to our two key communication channels for ongoing operations.

After the successful completion of the work above, the team will assess the following:
1. Honeybadger application integration 
2. Because this is a 24/7 environment, automated recovery should be included in the recommendation for the system monitoring and alerts. 
3. Exploration of the Ruby Gem (OK Computer)

**Comment by libdgg** [comment]
![2021-Blacklight Monitoring Alerting.jpeg](https://images.zenhubusercontent.com/5c0ec309cd03b2349870e625/2410096e-21fe-4e99-9f82-a1b293ec7584)
