### ISSUE TITLE
SPIKE: Review authorization process (Alma User Groups) and identify requirements for automating process with Blacklight

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#756]
A meeting has been scheduled on 7/27 for the following:

- [ ] Review the current process used by Primo and Kleene for authorization based on Alma user group rules. 

- [ ] Review any changes by Access Services Policy Committee to the Alma User Group Rules that will simplify the number of groups and/or number of rules 

- [ ] Propose a solution for Blacklight using Alma User Group rules for authorization that is automated in an effort to read any differences to the rules as changes are made to the user group rules.

**Comment by lisahamlett** [comment]
The user groups for the Atlas products (i.e. Ann's spreadsheet) and the user groups in Alma are not exactly the same thing.  I've proposed that these non-feed users in Alma get merged into one group because they function exactly the same in Alma:
05	Alumni
06	Trustee/VIP
07	Courtesy
08	Fee
14	Affiliate
15	ARCHE/GETS
16	FacSpouse
17	StSpouse

In the event that change is made in Alma, they will all get merged into the same number, which will need to be simplified in the Atlas table.  BUT, in general, changes in Alma will not make a difference for the Atlas table.  Only if the user group numbers change, which would only happen in an extreme case.

NOW... If Ex Libris fixes the Request Options API, you can use the logic from Alma I built for the services pageto tell you which options to show for the patron and completely bypass the table.  Here's the ticket information as of this morning:
[https://app.zenhub.com/files/295449627/debb00ea-f161-4ba5-aade-9284b797a73c/download](https://app.zenhub.com/files/295449627/debb00ea-f161-4ba5-aade-9284b797a73c/download)

**Comment by lovinscari** [comment]
The team assigned to this ticket met on 7/27/20. Link to the minutes are located at https://emory-my.sharepoint.com/:w:/g/personal/rmetz_emory_edu/EUIC4LVIweFPhL8W5PdiYOkBSRDjsluIIVEFLpZyQSPtrQ?email=tiffany.miles%40emory.edu&e=5D2S8O
