### ISSUE TITLE
Spike: investigate why wildcard searches do not work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#813]
As noted in the fuzzy search research spike ticket, we have noted that wildcard searches such as the following do not seem to work in Blacklight from our various search options.

**Search for Titles that begin with A and sort ascending A to Z:**
Blacklight - basic Title search: https://blackcat-test.library.emory.edu/?q=A%2A&search_field=title&sort=title_ssort+asc%2C+pub_date_isim+desc

Blacklight - Advanced Search by Title: https://blackcat-test.library.emory.edu/catalog?utf8=✓&op=AND&all_fields_advanced=&title_advanced=A*&author_advanced=&subject_advanced=&title_series_advanced=&publisher_advanced=&identifier_advanced=&call_number_advanced=&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&sort=title_ssort+asc%2C+pub_date_isim+desc&search_field=advanced&commit=Search

The above searches return results, but clearly do not follow the pattern of "starts with A".

Having the ability to construct searches like this on titles especially would be very helpful to support browsing and advanced search needs for users who may not know the exact title they are looking for.

Testing in SOLR, the following query _does_ work on a field which has been defined as a facet (format_ssim).
https://solr-cor.library.emory.edu/solr/blackcat_collection/select?fl=format_ssim&q=format_ssim%3AB*

Spike goals:

1. Research wildcard search functionality in Blacklight and SOLR
2. Identify options for supporting "starts with..." type searches in either basic or Advanced search and if our search forms need to be changed to do so
3. Recommend if new SOLR fields are needed to support this type of search on titles (e.g. title_browse_ssim)
4. If wildcard searching can be enabled for Titles, recommend if wildcard searches could be performed on authors also

**Comment by bwatson78** [comment]
Preliminary Findings: Maybe `title_main_display_tesim` should be `title_main_display_ssim`. We do not use this field for search, and I've tested other fields that were strings, not text and it proves to be working. I'm going to change it locally and test it thoroughly. Tokenization is the culprit here.

**Comment by bwatson78** [comment]
Findings: I assure you that wildcard searching within Blacklight is working. The problem is that the expectation of using it, for example, in the Title search option in the `A*` fashion will return all records in the catalog that have a main title starting with `A` isn't correct. All of the fields being examined in the Title option
```
['title_tesim', 'title_vern_display_tesim', 'title_addl_tesim', 'title_abbr_tesim',
      'title_added_entry_tesim', 'title_enhanced_tesim', 'title_former_tesim',
      'title_host_item_tesim', 'title_key_tesim', 'title_translation_tesim', 'title_varying_tesim',
      'title_later_tesim', 'title_series_tesim']
```
are tokenized, which means that 990017045700302486's `title_addl_tesim` value of `!Kung short films by John Marshall ; produced and distributed by Documentary Educational Resources ; photographed and directed by John Marshall` is not seen as one continuous string starting with `!`, but an array of substrings separated by whitespace and each analyzed and lumped together with common English variants of those strings. This record's main title is `!Kung short films`--none of the substrings within that string start with the letter A, but the `title_addl_tesim` value above has two `and`'s within the string and would return in a search of `A*` in the Title option. 

So how do we do a "Starts with..." type of action with Blacklight search? We shouldn't--at least by using the search functionality. It is true that if you access the Solr queries through Solr's UI, you can receive results by searching by field utilizing the letter-wildcard combo **with string-configured fields only (i.e., `_ssi` and `_ssim`)**. The issue doing the same in Blacklight is that we'd have to create a new search option that looks only at a string version of the main display title (i.e. `title_main_display_ssim`) and that search option could only work reliable one of two ways: 1. Searching for main titles starting with the letter/number you put infront of a wildcard, and 2. searching for the exact value contained in that field. You couldn't combine together that search with another query pointed at a different set of fields. So I recommend creating a new field that contains just the first letter of each record's main display title, and using that as a facet.

**Comment by eporter23** [comment]
Followup after discussions with @bwatson78 - [mockup of possible approach](https://docs.google.com/drawings/d/1cAsJKM_AA1fcHaTXRPXFeCsA9Y0jN-z0tt-L9slnOIE/edit) to adding to Advanced Search.

**Comment by rotated8** [comment]
@eporter23 @bwatson78 So, it turns out `A*` is a poor search to demonstrate wildcard search not working, because "A" is a common, valid word. Instead, lets look at some searches with `catech`. "Catech" can be a shortening of the Latin word "catechismus" or the English "catechism". If wildcard searching is working, we should see a difference in the number of results for `catech`, `catech*`, and `"catech"`. In this case, tokenized text is a boon, since we want to to find matches anywhere in the field. So how do we do?

- [catech](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catech) - 4 results
- [catech*](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catech*) - same 4 results
- ["catech"](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q="catech") - same 4 results

Looking through the results, you can find "catech" in each, usually in the additional title. But none of these are English, none of the results matched "catechism" or "catechismus". Do we really have zero results for those terms?

- [catechism](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catechism) - 5415 results
- [catechismus](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catechismus) - 459 results

So, `catech*` is missing almost 6000 results! What's going on? Let's look at the [keyword search configuration](https://github.com/emory-libraries/blacklight-catalog/blob/main/app/controllers/catalog_controller.rb#L290-L296) in the catalog controller. It clearly specifies `qf` and `pf` parameters for Solr, but neither are present in Solr's [standard query parser](https://solr.apache.org/guide/7_7/the-standard-query-parser.html#standard-query-parser-parameters). Instead, they show up in the [dismax](https://solr.apache.org/guide/7_7/the-dismax-query-parser.html) and [edismax](https://solr.apache.org/guide/7_7/the-extended-dismax-query-parser.html) parsers. In short, the difference between the two is that dismax does not support many of the query features that exist in the standard query parser, one of which is wildcards. We can verify this by translating our application searches into Solr queries. (I've used `fl` to make the results easier to skim, but it has no effect on the search.)

- [dismax "catech*"](https://solr-cor-test.library.emory.edu/solr/blackcat_collection/select?defType=dismax&fl=id%2C%20title_display_tesim%2C%20score&q=catech*&qf=text_tesi%20id%20local_call_number_tesim) - `numFound: 4`, and they match the application's results
- [edismax "catech*"](https://solr-cor-test.library.emory.edu/solr/blackcat_collection/select?defType=edismax&fl=id%2C%20title_display_tesim%2C%20score&q=catech*&qf=text_tesi%20id%20local_call_number_tesim) - `numFound: 9466`! That's more like it!

Looking back in the catalog controller, [a comment](https://github.com/emory-libraries/blacklight-catalog/blob/main/app/controllers/catalog_controller.rb#L286-L288) suggests that we can change which parser we use both by setting a different default, and by overriding it search type by search type. I believe this is the necessary work to fix wildcard searching.

**Comment by bwatson78** [comment]
I'm simpatico with you, @rotated8

**Comment by bwatson78** [comment]
Prototype features of Title Starts With facets and Main Title Wildcard search option now on Arch.

**Comment by bwatson78** [comment]
@eporter23 Will update the First Character field with what you mentioned in your DM.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/826

![Screen Shot 2021-08-12 at 8.38.10 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ae1748ca-26c2-4ff7-8c32-6307472fbaa9)

**Comment by eporter23** [comment]
@bwatson78 this works great on Advanced Search. I am assuming we didn't go any further with the wildcard searching for keyword search but let me know if that is not the case. I think what we have in place is a great enhancement for now.
