### ISSUE TITLE
Review documentation related to implementing the Go VE button in Alma to determine any risks if implementing in production

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#830]
According to Yisrael at ExLibris, by design, the Go VE process is only available on production. This is in order to ensure that sites are testing their real data and setup and not on 'dummy environments' that then need to be tested again on production. There is concern of the impact of implementing this in production so it is requested a review of the steps needed be completed and any risks identified before moving forward.

Acceptance criteria:

- [x] Please review the article - https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_1%3A_Enablement_Phase

- [x] Document within this ticket any risks associated with implementing the Go VE process in the production Alma environment.

**Comment by libah** [comment]
Go VE consists of 4 Phases. 
Step 1: Enablement
Step 2: Authentication
Step 3: Configuration
Step 4: Go Live - put VE in production

Step 1: Enablement
During the enablement phase, after pushing the Go VE button, you choose the views you want to be copied from the existing production Primo. 

The system then takes over and does the following: 
Enable the Discovery menu in Alma. 
Create selected end-user views in Primo VE.
Copy customizations from Primo to Primo VE.
Copy translations from Primo to Primo VE.
Enable Primo VE searches within your local catalog and CDI.

Risks: 
Since the Primo classic and Primo VE are separate systems, there should be no risk to our currently running DiscoverE system. There is a slight risk that the indexing of the catalog and CDI records may take trump other indexing jobs running, but running this over the weekend should mitigate that risk.
