### ISSUE TITLE
TASK: Fix Word wrapping/arbitrary hyphenation in long facet values

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#858]
Per Item #6 on the [CSS Punchlist](https://docs.google.com/document/d/1TfiTa7wdHPcVA8uNbkrH2MtZDYbBI5SPLRV4Ka2yfq4/edit?usp=sharing)  - Fix word wrapping/arbitrary hyphenation in long facet values

**Comment by eporter23** [comment]
@CB987 I'm adding the requires reindexing label, because in order to help with some of the word breaks we have proposed changing some of the Resource Type values which are coming from metadata. Should we write up that work as a separate ticket? Proposed changes are shown below - **Video or Visual Material**; **Archival Material or Manuscripts**:

![Screen Shot 2021-09-01 at 10.17.53 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/35bd22c3-c7ca-4b2c-8b79-3b3c8fe978b2)

**Comment by CB987** [comment]
![Screen Shot 2021-09-02 at 4.24.13 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/b1ff5395-3bca-4426-b8b6-1229f73ade6c)

**Comment by lovinscari** [comment]
Looks great.
