### ISSUE TITLE
Preliminary search results snippet - metadata fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#87]
_As an end user, I want to preview significant information about a resource that matches my search query, so that I can determine if I need to view it in greater detail_

Notes:

- These requirements are still in review for final approval, so iterations may be needed.
- Additional tickets will specify additional preview components beyond the metadata fields.

**Metadata fields to display in search results:**

- [x] Search result number
- [x] Title (hyperlinked to item detail view) 
- [x] Author/Creator (prefix with "Author/Creator:")
- [x] Resource Type (prefix with "Resource Type")

For mappings, use the preliminary mapping sheet OR what has been provided in ticket #102.

**Comment by bwatson78** [comment]
Couple of notes:

1. I'm adding a field called "Access" that will display whether the MARC record denotes the item as an "Electronic" or "Physical" Resource. The goal is to incorporate the data from this field into the "Resource Type" field (e.g. Access of "Electronic Resource" and format of "Book" should read as "Ebook"). Since the exact mapping of a true electronic resource has proven complex (to say the least), it might be useful to see what our original logic deems as electronic.

2. The only field that contains publishing data from the original mapping only pulls published location data. To get the "Publisher" field, I will have to add an additional field to the schema and map it. That means that we will have to reindex all of the Solr documents after the initial production import. Until that is done, no records will display "Publisher" on the index page.

**Comment by eporter23** [comment]
@bwatson78 regarding point 2 above, it would probably make sense to hold off on that until more of the mapping work is finalized and we can confirm with @lovinscari about why Publisher doesn't show up yet.

**Comment by bwatson78** [comment]
Alright. So we're excluding "Publisher" from the requirements?

**Comment by eporter23** [comment]
@bwatson78 and @lovinscari I amended the ticket to note Publisher as a deferred requirement that we will need to add later. We have confirmed that publisher name isn't yet available in the data set we have to work with.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/111

![Screen Shot 2020-12-18 at 3.32.22 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/67fdb2bf-f35d-473f-9c91-5ed28c0477da)
