### ISSUE TITLE
Implement and configure the PrimoVE Services View for Atlas Products Integration for Sandbox

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#898]
Integrate the Services View with Atlas products including products for ILL/Document Delivery, Course Reserves, and Special Collections. 

The Services Page should only provide links to the associated Atlas products if the user and the item record indicate the access and authorization (ie, using the Alma User Group Rules). The item record information should be passed from the item record to the Atlas product. It is assumed the user will need to login or create an account with the Atlas product. 

Test 

EDIT: I noted this is for Sandbox, as these are already built in production.  - LH 9/22/21

**Comment by lisahamlett** [comment]
The Aeon integration is ready.  **NOTE:** Because this uses Bernardo's script, there's no way to send requests to Aeon Test!  If you're going to test this, **DO NOT submit the Aeon form!!!**

Special Collections Item:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990016709110302486

Special Collections Multiple Items:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990005059530302486

**Comment by lisahamlett** [comment]
The Ares integration is ready and pointed to Ares Test.

Stacks monograph: (You must choose a location in order to pick an item for course reserves)
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022757740302486

Stacks serial: (You must choose a location in order to pick an item for course reserves)
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990027505610302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/4ceeb4a3-d4d2-4f37-9d9d-fbd55804073a)

**Comment by lisahamlett** [comment]
The ILLiad document delivery integrations for students is ready and pointed to ILLiad **PRODUCTION** because I do not know the link to ILLiad test.  I have asked ILL for the address.

To view this integration, your user group needs to be Distance-Ed, Graduate Student, Oxford Undergraduate, or Undergraduate Student and you can use the same items as for the Ares integration.

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/0e0a0c17-1a7f-427b-bcbf-7f99426409c6)

**Comment by lisahamlett** [comment]
The ILLiad document delivery integrations for students is ready and pointed to ILLiad **PRODUCTION** because I do not know the link to ILLiad test. I have asked ILL for the address.

To view this integration, your user group needs to be Faculty or Staff and you can use the same items as for the Ares integration.

**Comment by lisahamlett** [comment]
I spoke to Jenny Vitti and she has agreed to let us test ILL requesting by adding TEST to the beginning of the titles for any requests.  I have edited the OpenURL to automatically add test to any requests.

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/9d8bd822-e5cf-4184-8aad-fa734d4a5e25)

**Comment by lisahamlett** [comment]
Final notes:
- Course Reserves requesting is complete in both sandbox and production.  Production points to Ares production and sandbox points to Ares test.
- ILLiad requesting is complete in both sandbox and production.  BUT!!!  ILLiad does not have a test instance, so I have set the ILLiad URL in sandbox to add "TEST-" to the beginning of titles using the production form.  Testers SHOULD NOT submit requests to ILLiad, but ILL knows to close out any request that start with "TEST-" just in case.
- Aeon requesting is complete in production and points to Aeon production.  Aeon requesting in Sandbox is currently also pointed to Aeon production with the (THIS GOES TO AEON PRODUCTION!!!) note shown above because Hopper (where the test script lives) has an expired cert.  Once the cert is updated, I will change the link to point to Aeon Test.

**Comment by libdgg** [comment]
Alex started testing. Aeon requesting is going to prod. Hopper (the request server) has an expired cert and Beth is working on that. This is not a show stopper. People just need to know not to put in a request.
So far it is looking good. Keep in review until at least Monday for final review.

**Comment by libdgg** [comment]
This ticket can be closed per standup 2021-09-27
