### ISSUE TITLE
TASK: Determine work needed for link resolver and FindIT at Emory 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#900]
Determine work needed for link resolver and FindIT at Emory including documenting work needed by Electronic Resources Department and LTDS. 

The desired goal is to have links that currently direct users to Primo Classic UI (discoverE) be directed to PrimoVE Services View. 

If possible, an intermediate link resolver process should be configured to avoid having to redo this work when moving off of PrimoVE. 

Test

**Comment by libdgg** [comment]
This ticket is blocked until we get the domain name ticket work done.

**Comment by libdgg** [comment]
We did get info from ExL on how to setup redirects in Alma.
For more information regarding this option, please review the following web page:
https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/120Other_Configurations/Configuring_Redirection_for_Primo_VE_Deep_Links

That work appears to be blocked - if we did it now and someones clicks on FindIT they would end up in Primo VE - we need a cutover plan.

**Comment by libdgg** [comment]
Update for this ticket. It may not be blocked as much as the timing isn't ready. We have info on redirects and we are requesting a meeting with ExL. 
Recommend keeping this ticket in "blocked" until we meet with ExL and then determine if we should resume work on this or move the ticket back into Backlog.

**Comment by libdgg** [comment]
Efi responded to my basecamp request to schedule a meeting on 2021-09-20
We currently on holiday here in Israel untie Sep 29. I will login from time to time so please feel free to update basecamp with any question or request and I will be happy to assist.
For any urgent topics you can:
1. Open new Basecamp discussion with the word "URGENT" in the title.
2. Send an email with the word "URGENT" in the subject of the email to: go_ve@exlibrisgroup.com.

**Comment by libdgg** [comment]
Ann sent a message to Efi on basecamp yesterday.

**Comment by libdgg** [comment]
Efi responded to Ann's message
https://3.basecamp.com/3765443/buckets/23697781/messages/4170336223

**Comment by libdgg** [comment]
Bsed on Efi's response:
Find IT links during beta will still point to discovere.
We would need plan for the "Deep Link mapping" for our production cut-over.
Longer term follow up on updating vendors.

**Comment by libdgg** [comment]
Per discussions in the sprint planning on 9/22, moving this to backlog and add this into an agenda as part of our request for a meeting with ExL.

**Comment by libah** [comment]
Find It @ Emory  in primo VE
pubmed/sandbox
https://emory-psb.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&url_ctx_val=&isSerivcesPage=true&id=pmid:25638347&url_ctx_fmt=null&sid=Entrez:PubMed

pubmed production

https://emory.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&url_ctx_val=&isSerivcesPage=true&id=pmid:25638347&url_ctx_fmt=null&sid=Entrez:PubMed

**Comment by libdgg** [comment]
UPDATE 2021-10-11
Efi responded on basecamp with a link to [DNS switch simulation](https://knowledge.exlibrisgroup.com/@api/deki/files/87177/DNS_switch_simulation.docx?revision=2) (a Word doc).

Not sure if related but Efi provided a link to [Configuring Redirection for Primo VE Deep Links](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/120Other_Configurations/Configuring_Redirection_for_Primo_VE_Deep_Links) in another thread in basecamp.

**Comment by libah** [comment]
I followed the directions to do the DNS switch simulation, but it didn't work. I have written to Efi and sent him the urls so that he could try it on his end. There are instructions for configuring redirection Primo VE deep links, but no way to test them without using something like the DNS switch simulation. There are three linking redirect situations that we are dealing with:

- saved searches
- saved permalinks 
- redirecting the FindIT @ Emory links
The actual work shouldn't take long once it's working. My main concern is testing in advance to see if the Findit redirects will work. The alternative is not desirable, which is asking the ER staff to write to vendors with the new url. Ex Libris states that redirecting the Findit links should only be a temporary solution, that the best practice is to change the links with the vendor. At this stage, I am not confident that the redirect will work for the Findit links. Hopefully Efi can get the simulation to work.

**Comment by libah** [comment]
The two primary types of links used most heavily are the findit at Emory links and the permalinks. Each type of redirect requires setup in the Primo Deep-Link Re-Direct Configuration. A simulation of a redirect can be setup on a local computer using the attached instructions from Ex Libris. 

The Findit at Emory link simulation is working. Whether the perma links will redirect or not is still an open question because they are using the discovere.emory.edu domain, whereas the Find it at Emory links use the ex libris primo classic domain. 
This is another question that I have posted in Basecamp for Ex Libris. 

[https://app.zenhub.com/files/295449627/f11d90b8-aa9d-4bc7-8cc8-231f998aebb4/download](https://app.zenhub.com/files/295449627/f11d90b8-aa9d-4bc7-8cc8-231f998aebb4/download)

**Comment by libah** [comment]
Determine work needed for link resolver and FindIT at Emory including documenting work needed by Electronic Resources Department and LTDS.

The work needed for the link resolver (permalinks) and FindIT at Emory is:
1. setting up the Primo deep-link configuration, for both the permalinks and FindIT at Emory links. 

2. Testing using the simulation solution provided by Ex Libris. 

    The simulation is the best test we can do without actually being able to test in production. 
     Using the test simulation shows that the deep-link configuration is setup properly so that the 
     Primo links will forward correctly to Primo VE. 

3. When we go live we will need to request the dns for search.libraries.emory.edu to point to Primo VE

4. I recommend that  Testing should also involve someone in ILL probably Jenny, since she will need to change a setting on her computer to use the simulation. 

5. If possible, an intermediate link resolver process should be configured to avoid having to redo this work when moving off of PrimoVE.

   Since the work for the redirects is being done in PrimoVE with it's redirect module, I don't think we will be able to redirect these links again. The eresources department, as well as people in charge of links they have in things like libguides may need to change the links.  A solution will need to be developed for FindIT at Emory to work without VE. In the case of the eresources, it means contacting the vendors with the new link, once a solution is found and we can give the eresources people the link.
