### ISSUE TITLE
SPIKE: Investigate issues with page load time performance and provide suggestions for improvement

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#931]
The page load time for search.libraries.emory.edu and blackcat-test.library.emory.edu have become slower to load over the last month or so. The average page load time is about 7 seconds (slightly better for blackcat-arch) and the desired page load time should be under 5 seconds. For comparison of other Blacklight catalog products the following is used for benchmarking:

- [Temple University Library Search](https://librarysearch.temple.edu/catalog) - less than 2 seconds (no search initiated and not logged in)

- [Stanford Searchworks](https://searchworks.stanford.edu/) - less than 2 seconds (no search initiated and not logged in)

- [ ] I would like for the infrastructure and possibly application development team to research any errors or issues that might be indicative of a performance issue on the home page for either environment (production or test)

- [ ] If there are no errors or issues apparent, I would like for both teams to investigate how we might improve page load times including looking at connections to Solr, our AWS setup, API's to Alma, or facets that appear on the home page as possible reasons why our page times are so much slower than Temple or Stanford. Collin Brittle has suggested the issues might be related to the number of guest user accounts being stored and perhaps clearing those accounts might improve performance.

- [ ] Document all findings within this ticket along with a recommendation to improve performance.

**Comment by jcrompton42** [comment]
A few observations for discussion:  

- there appears to be no 1 page for the landing: apache is loading a whole directory of .js and .css files.  If a single page is provided, load times are faster, e. g. https://search.libraries.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=trout or https://search.libraries.emory.edu/index.html

-there doesn't seem to be any caching being done by the application.

- 2 configuration warnings on the webserver
shibboleth: WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites

(this one I fixed because it was easy)AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.

- the database instance connected to prod is a t3 micro with 1 GB of RAM.

**Comment by tmiles2** [comment]
Other recommendations:

- Reviewing Solr 
- Look at waterfall method for loading a page (application development)

**Comment by alexBLR** [comment]
![Screen Shot 2021-09-27 at 10.28.27 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/3020c14b-32d9-46de-ab00-45ea8219309e)

![Screen Shot 2021-09-27 at 10.28.45 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/dff948bc-927e-401a-ad87-f7fd01d44362)

The wait time, also known as time to first byte is how long it takes for the server to send the first byte from when the connection is initiated. If this is high, it means your server has got to do a lot of work to render the page before sending it. We need investigate why app is doing so much work to render the page.

![Screen Shot 2021-09-27 at 10.28.55 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/92eb4fad-b345-4015-a7f5-f0f9dda54adb)

Other things to look at **Range Limit** and the **Hero Image**
![Screen Shot 2021-09-27 at 10.33.54 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/8c2b09aa-c81a-4a98-9aee-e95dba4f8786)

**Comment by jcrompton42** [comment]
Looking at the load on the solr instances during load, I am seeing fairly high (> 2 for 2 vcpu instances ) loads on the solr ec2s. These are small t3 large ec2 instances and that should likely be increased.
