### ISSUE TITLE
SPIKE: Determine mapping requirements for Bound-With Titles

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#98]
As an end user, I want the ability to search for bound-with materials (multiple separate bibliographic entities in the same microfilm real) as part of a Title search in the Global Search Bar. This is a spike ticket because it is unclear how this is handled in Solr and Blacklight. Any customizations needed to satisfy the user requirements will be documented in new tickets. 

Examples of Bound-With Titles are included in the comments below from Laura Akerman

A bound-with is a set of bib records where the "child" records are part of a "parent". The children have MARC data that points to the parent, and the parent has item data.

A "child" bound-with may or may not be requestable separately from the parent.

I would like for the software engineering team along with Emily Poter to determine the mapping and indexing requirements for displaying Bound-With titles together as one record including parent and children.

Working documents:
[Wireframe for example 1](https://docs.google.com/drawings/d/1C1mhctyjvfYvrhU85hYJuEu0YOVApxtmq_ez6eZ-YVQ/edit)
[Wireframe for example 2](https://docs.google.com/drawings/d/17MD9WaqZp2YgCnk5_9AfzPoOTkDIZ3TaTuzbk76atTg/edit)
[Wireframe for example 4](https://docs.google.com/drawings/d/1Pu54Y_zh3kAav9S8P0CNH-069yefXmNTNhljrbpIb44/edit)

**Comment by lovinscari** [comment]
@laura-ake - Can you please provide examples of Bound-With titles?

**Comment by laura-ake** [comment]
Here are some I had saved:

1.  The story of a carpet  MMSID: 990025512850302486
     The gospel in Asia Minor  MMSID: 990025511590302486  (the "parent" record that gets the barcode)

2.  The five wrong men; why railroad labor cannot accept the recommendations of the President's emergency board  MMSID: 990022023340302486.  In the Alma view of the published-to-Primo record you can see the 773 field linking it to the parent record and a PLK field (one of the Primo publishing special fields) 
     Millions for Propaganda  MMSID: 990022022060302486 (the "parent" record that gets the barcode).  

         <datafield tag="773" ind1="1" ind2="8">
            <subfield code="w">990022022060302486</subfield>
            <subfield code="t">Bound with: HE2715 .B7 W3 ; Millions for propaganda /</subfield>
          </datafield>

          <datafield tag="PLK" ind1=" " ind2=" ">
            <subfield code="a">Contains.</subfield>
            <subfield code="b">990022022060302486</subfield>
          </datafield>

3.   Report of Gordon N. Peay, as receiver in chancery of the Real Estate Bank, 30th June, 1860.  MMSID:  990023443410302486
     Message of Elias N. Conway, governor of Arkansas, to both houses of the General Assembly, November 6, 1860  MMSID:       990023162360302486 (the "parent" record that gets the barcode)

I sent the child record MMSID to Lisa.  In addition to being a bound-with, it's rare book cataloging, it's in the Rose Library, and, although it's not coded as that Resource Type in Primo, it's a government document (depending on your definition).

It would be good to have an example of serial bound-withs, e.g. a serial title change that happened in the middle of the volume, and a U.S. Govt. document series (serial) that has individual titles for reports inside a volume, and if I could find something where we have a separately bound copy as well as a bound-with copy too that'd be nice.  But that would require more digging.  
@eporter23  or @lovinscari is this enough for now?

**Comment by laura-ake** [comment]
4.  Here's a famous bound-with:  	Title:  Lectures on non-standard analysis.  MMSID:  990009768670302486.  This is part of the series Lecture Notes in Mathematics (it's No. 94(, of which there are hundreds; the older ones are classified together and bound together several to a volume (it was an analyzed serial, back when we did that kind of thing).  Its "parent" record is  990031756460302486.  In the 773 tag, the "parent" title is listed as "Lecture notes in mathematics NO.93-96".  There's actually a record for this bound volume (what we call a "dummy" record) with the barcode, to which the individual "lecture notes" records are linked.  So this is one case where the "is part of" relationship makes sense.  When we were on Aleph, this was the only way Aleph could handle bound-withs of this type.  It was an enormous amount of work to make those dummy records.  They're not needed in Alma but I suppose we don't have time to go back and do them the other way (using the first title in the bound volume as the "parent" with the barcode, and linking the others to it).  So this is another pattern you'll see in Alma.

**Comment by rotated8** [comment]
This may be a good place to use the `blacklightfederalregister` set, since it includes holding and item information.

**Comment by lovinscari** [comment]
I believe this has been addressed but we will revisit if needed as part of functional testing.

**Comment by eporter23** [comment]
@lovinscari FYI I have not done any work related to bound-with mappings yet.

**Comment by laura-ake** [comment]
Am I correct that we are waiting to implement something for bound-withs after the display and function of holdings and items is stable in Blacklight?

Laura

From: lovinscari ***@***.***>
Sent: Friday, April 23, 2021 3:28 PM
To: emory-libraries/blacklight-catalog ***@***.***>
Cc: Akerman, Laura ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/blacklight-catalog] SPIKE: Determine mapping requirements for Bound-With Titles (#98)


I believe this has been addressed but we will revisit if needed as part of functional testing.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femory-libraries%2Fblacklight-catalog%2Fissues%2F98%23issuecomment-825872315&data=04%7C01%7Cliblna%40emory.edu%7Ccd791bbb2f7249c9ec5d08d9068dee5f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637548028928296933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1DFwAX6Npl6pUbaVCMYyaXIgdqgR5IegpIE8JL5zTsQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFZRJ2GEXD32YZYSCF2Y3YLTKHC4TANCNFSM4U4Q677A&data=04%7C01%7Cliblna%40emory.edu%7Ccd791bbb2f7249c9ec5d08d9068dee5f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637548028928306932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KamG3bhrIrvQquDTEdAdPoRY4mUfvHJ%2BMkl%2BrTDR034%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by eporter23** [comment]
Initial notes: we have ~56,000 records with 773 $w and $t. We have included 773 in the field Host Title field, which is searchable in a title search. We could look at adding a new display field that creates a hyperlinked keyword search on the ID stored in $w and use $t as the link text. We could also make sure that this field is shown near the Access/Where to Find it sections for child records with no barcodes, which will not show any holdings.

**Comment by eporter23** [comment]
After discussing with Laura and Sofia, I have updated the 3 mockups in the ticket description with ideas for implementation. In a nutshell, this will include 1) adding a new Is Part Of field in SOLR 2) adding a new hyperlinked search behavior on the title component of the new field 3) generating a link to the Services page for these items: Alma has existing logic to show users related parent records for these kinds of situations.

**Comment by eporter23** [comment]
Some records have more than one 773 which can include different types of IDs such as OCLC numbers in $w. We can potentially isolate the 773s that contain an MMSID (starts with 99 and ends with 2486).

**Comment by eporter23** [comment]
[773 with MMSIDs in $w](http://solr-cor-arch.library.emory.edu/solr/marc_collection/select?fl=id%2Cs_773_*_ssim&q=s_773_w_ssim%3A99*2486)
